name: "CICD"

on: 
  push:
    branches: [main]
    tags:
      - "*.*.*"
  
jobs: 
  test:
    name: Simulate a test post-merge 
    uses: ./.github/workflows/pytest.yml
  build: 
    name: Simulate build
    needs: 
      - test
    runs-on: ubuntu-latest
    steps: 
      - name: Simulate build
        run: >-
          echo "Build output" > artifact.txt
      - name: Store the artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.txt

  push-to-production:
    name: Simulate a push to production
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: artifact.txt
      - name: Simulate push to production
        run: >-
          echo Pushing to production...
          cat artifact.txt
