name: "Test and Lint"

on: [push, pull_request]

jobs:
  test:
    name: Simulate a test 
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo Testing...
      - name: Fail
        run:  exit 1
      - name: Debug  
        run: echo Should not reach this message
